### ISSUE TITLE
Not working in PHP > 8.0

### ISSUE THREAD

**Issue by sajumani** [square1-io/laravel-passport-firebase-auth#4]
Hi,

Am trying to use this in my project. Laravel/passport needed > 8.0 version, so i upgraded but [laravel-passport-firebase-auth](https://github.com/square1-io/laravel-passport-firebase-auth) works only with PHP 7.3

**Comment by sajumani** [comment]
@Benjacho Any  update for this ?

**Comment by BillKG** [comment]
use `composer install --ignore-platform-reqs`

**Comment by sajumani** [comment]
@BillKG Thanks for your reply

it taken but finally, am getting this error

My xampp PHP version 7.4.  Should i update PHP to 8.0 ?

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in D:\***\vendor\psr\log\src\LoggerInterface.php on line 30
PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in D:\***\vendor\psr\log\src\LoggerInterface.php on line 30
PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by BillKG** [comment]
Yes I recommend using php 8 for this.

**Comment by Benjacho** [comment]
@sajumani we are currently depending on that php version, you can fork it and change the version to php8 meanwhile php 8.0 is not supported. We have plans to support it in near future
